#!/usr/bin/env bash
# crash-alert.sh - SessionEnd hook for instant crash/exit alerting
# Called by Claude Code's SessionEnd hook in each agent's .claude/settings.json
# Receives JSON on stdin with: session_id, transcript_path, cwd, hook_event_name
# Environment: CRM_AGENT_NAME, CRM_ROOT, CRM_TEMPLATE_ROOT set by agent-wrapper.sh

set -uo pipefail  # No -e: best-effort alerting even if parts fail

CRM_ROOT="${CRM_ROOT:-${HOME}/.claude-remote}"
AGENT="${CRM_AGENT_NAME:-unknown}"
TEMPLATE_ROOT="${CRM_TEMPLATE_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
LOG_DIR="${CRM_ROOT}/logs/${AGENT}"

mkdir -p "${LOG_DIR}"

# Read hook input from stdin (non-blocking, may be empty)
HOOK_INPUT=$(cat 2>/dev/null || echo '{}')
SESSION_ID=$(echo "${HOOK_INPUT}" | jq -r '.session_id // "unknown"' 2>/dev/null || echo "unknown")

# Log the session end
echo "${TIMESTAMP} SESSION_END agent=${AGENT} session=${SESSION_ID}" >> "${LOG_DIR}/activity.log" 2>/dev/null

# Check crash count for context
CRASH_COUNT_FILE="${LOG_DIR}/.crash_count_today"
TODAY=$(date +%Y-%m-%d)
CRASH_COUNT=0
if [[ -f "${CRASH_COUNT_FILE}" ]]; then
    STORED_DATE=$(cut -d: -f1 "${CRASH_COUNT_FILE}" 2>/dev/null || echo "")
    if [[ "${STORED_DATE}" == "${TODAY}" ]]; then
        CRASH_COUNT=$(cut -d: -f2 "${CRASH_COUNT_FILE}" 2>/dev/null || echo "0")
    fi
fi

# Build alert message
MESSAGE="SESSION END: ${AGENT} exited at ${TIMESTAMP}. Crashes today: ${CRASH_COUNT}. launchd will respawn."

# Send alert to the agent's Telegram chat
ENV_FILE="${TEMPLATE_ROOT}/agents/${AGENT}/.env"
if [[ -f "${ENV_FILE}" ]]; then
    { set +x; } 2>/dev/null
    set -a; source "${ENV_FILE}"; set +a
fi

if [[ -n "${BOT_TOKEN:-}" && -n "${CHAT_ID:-}" ]]; then
    source "${TEMPLATE_ROOT}/core/bus/_telegram-curl.sh"
    telegram_api_post "sendMessage" \
        -d chat_id="${CHAT_ID}" \
        --data-urlencode "text=${MESSAGE}" \
        > /dev/null 2>&1 || true
fi

# --- Auto-generate session closure summary ---
# Reads stats file and recent activity log to create a minimal session record
# in knowledge-sync/cc/sessions/ so no session goes unrecorded.
SESSIONS_DIR="${HOME}/code/knowledge-sync/cc/sessions"
STATS_FILE="${CRM_ROOT}/state/${AGENT}.stats.json"
SESSION_START_FILE="${CRM_ROOT}/state/${AGENT}.session-start"

if [[ -d "${SESSIONS_DIR}" ]] && [[ -f "${STATS_FILE}" ]]; then
    SESSION_DATE=$(date +%Y-%m-%d)
    SESSION_TIME=$(TZ=America/Los_Angeles date +%H:%M)

    # Read stats
    UPTIME=$(jq -r '.uptime_s // 0' "$STATS_FILE" 2>/dev/null || echo "0")
    INJECTS=$(jq -r '.injects // 0' "$STATS_FILE" 2>/dev/null || echo "0")
    AGENT_STATE=$(jq -r '.agent // "unknown"' "$STATS_FILE" 2>/dev/null || echo "unknown")

    # Format uptime
    HOURS=$((UPTIME / 3600))
    MINS=$(((UPTIME % 3600) / 60))
    DURATION_STR="${HOURS}h${MINS}m"

    # Get last 10 activity log lines for context
    ACTIVITY_LOG="${LOG_DIR}/activity.log"
    RECENT_ACTIVITY=""
    if [[ -f "${ACTIVITY_LOG}" ]]; then
        RECENT_ACTIVITY=$(tail -10 "${ACTIVITY_LOG}" 2>/dev/null | sed 's/^/- /')
    fi

    # Only write if a session file for this agent doesn't already exist today with this suffix
    CLOSURE_FILE="${SESSIONS_DIR}/${SESSION_DATE}_${AGENT}_auto-closure.md"
    if [[ ! -f "${CLOSURE_FILE}" ]]; then
        cat > "${CLOSURE_FILE}" << HEREDOC
---
type: session
date: ${SESSION_DATE}
time: ${SESSION_TIME}
agent: ${AGENT}
duration: ${DURATION_STR}
tags: [session, ${AGENT}, auto-closure]
auto_generated: true
---

## Session End (auto-generated)

Agent **${AGENT}** session ended at ${SESSION_TIME} PST after ${DURATION_STR}.
- Messages injected: ${INJECTS}
- Final state: ${AGENT_STATE}
- Crashes today: ${CRASH_COUNT}

## Recent Activity
${RECENT_ACTIVITY}

## Notes
This file was auto-generated by crash-alert.sh because the session ended without a manual /session-save. Check the daily note for ${SESSION_DATE} for fuller context.
HEREDOC
        echo "${TIMESTAMP} Auto-generated session closure: ${CLOSURE_FILE}" >> "${ACTIVITY_LOG}" 2>/dev/null
    fi
fi

exit 0
